# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'photo_editor.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1126, 761)
        MainWindow.setStyleSheet("background-color: back")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(-60, -40, 911, 411))
        self.label.setObjectName("label")
        self.right_btn = QtWidgets.QPushButton(self.centralwidget)
        self.right_btn.setGeometry(QtCore.QRect(10, 540, 93, 28))
        self.right_btn.setStyleSheet("color: black;\n"
"background-color: pink;\n"
"font-size:  15px;\n"
"font-weight: bold;\n"
"border-radius: 10 px;")
        self.right_btn.setObjectName("right_btn")
        self.riz_btn = QtWidgets.QPushButton(self.centralwidget)
        self.riz_btn.setGeometry(QtCore.QRect(50, 580, 93, 28))
        self.riz_btn.setStyleSheet("color: black;\n"
"background-color: pink;\n"
"font-size:  15px;\n"
"font-weight: bold;\n"
"border-radius: 10 px;")
        self.riz_btn.setObjectName("riz_btn")
        self.cb_btn = QtWidgets.QPushButton(self.centralwidget)
        self.cb_btn.setGeometry(QtCore.QRect(180, 580, 93, 28))
        self.cb_btn.setStyleSheet("color: black;\n"
"background-color: pink;\n"
"font-size:  15px;\n"
"font-weight: bold;\n"
"border-radius: 10 px;")
        self.cb_btn.setObjectName("cb_btn")
        self.left_btn = QtWidgets.QPushButton(self.centralwidget)
        self.left_btn.setGeometry(QtCore.QRect(120, 540, 93, 28))
        self.left_btn.setStyleSheet("color: black;\n"
"background-color: pink;\n"
"font-size:  15px;\n"
"font-weight: bold;\n"
"border-radius: 10 px;")
        self.left_btn.setObjectName("left_btn")
        self.window_btn = QtWidgets.QPushButton(self.centralwidget)
        self.window_btn.setGeometry(QtCore.QRect(230, 540, 93, 28))
        self.window_btn.setStyleSheet("color: black;\n"
"background-color: pink;\n"
"font-size:  15px;\n"
"font-weight: bold;\n"
"border-radius: 10 px;")
        self.window_btn.setObjectName("window_btn")
        self.save_btn = QtWidgets.QPushButton(self.centralwidget)
        self.save_btn.setGeometry(QtCore.QRect(60, 630, 211, 41))
        self.save_btn.setStyleSheet("color: black;\n"
"background-color: pink;\n"
"font-size:  15px;\n"
"font-weight: bold;\n"
"border-radius: 10 px;")
        self.save_btn.setIconSize(QtCore.QSize(30, 21))
        self.save_btn.setObjectName("save_btn")
        self.papka_btn = QtWidgets.QPushButton(self.centralwidget)
        self.papka_btn.setGeometry(QtCore.QRect(390, 530, 571, 28))
        self.papka_btn.setStyleSheet("color: black;\n"
"background-color: pink;\n"
"font-size:  15px;\n"
"font-weight: bold;\n"
"border-radius: 5 px;")
        self.papka_btn.setObjectName("papka_btn")
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setGeometry(QtCore.QRect(380, 570, 581, 101))
        self.listWidget.setStyleSheet("background: white")
        self.listWidget.setObjectName("listWidget")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1126, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "зображення"))
        self.right_btn.setText(_translate("MainWindow", "Вліво"))
        self.riz_btn.setText(_translate("MainWindow", "Різкість"))
        self.cb_btn.setText(_translate("MainWindow", "Ч/Б"))
        self.left_btn.setText(_translate("MainWindow", "Вправо"))
        self.window_btn.setText(_translate("MainWindow", "Дзеркало"))
        self.save_btn.setText(_translate("MainWindow", "Зберегти"))
        self.papka_btn.setText(_translate("MainWindow", "Папка"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
